[server]
maxUploadSize = 300

# Max size, in megabytes, of messages that can be sent via the WebSocket
# connection.
# Default: 200
maxMessageSize = 200

# Disable the folder blacklist in Streamlit
#st.set_option('server.folderWatchBlacklist', [])